name: "Checkout Private Repository"
description: "Checkout Private Repository"
author: "Tremi Dkhar"
version: "0.1.0"
inputs:
  repository:
    description: "Repository URL"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
  reference:
    description: "Reference"
    required: true
runs:
  using: 'composite'
  steps:
    - name: "Checkout the Private Repository"
      uses: 'actions/checkout@v2'
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.github-token }}
        ref: ${{ inputs.reference }}
        path: ${{ github.workspace }}/.github/actions/${{ inputs.repository }}
